# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-27 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=70)),
                ('message', models.CharField(max_length=180, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='vitabu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifuku', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
